import type { Lesson, Track } from "./lessons";

type Spec = { name: string; category: string; description?: string; values?: string[]; related?: string[]; obsolete?: boolean };

const htmlGroups: Record<string, string[]> = {
  "Document Structure": ["html", "head", "body", "title", "meta", "link", "style", "base"],
  "Headings & Text": ["h1–h6", "p", "br", "hr", "strong", "b", "em", "i", "mark", "small", "del", "ins", "sub", "sup", "abbr", "cite", "q", "blockquote", "code", "pre", "kbd", "samp", "var", "time"],
  Links: ["a", "nav"],
  "Images & Media": ["img", "picture", "source", "audio", "video", "track", "iframe", "embed", "object", "figure", "figcaption"],
  Lists: ["ul", "ol", "li", "dl", "dt", "dd"],
  Tables: ["table", "caption", "colgroup", "col", "thead", "tbody", "tfoot", "tr", "th", "td"],
  Forms: ["form", "label", "input", "textarea", "button", "select", "option", "optgroup", "fieldset", "legend", "datalist", "output", "progress", "meter"],
  "Semantic HTML": ["header", "main", "section", "article", "aside", "footer", "address"],
  "Interactive & Modern": ["details", "summary", "dialog", "template", "slot", "canvas"],
  "Global Concepts": ["comments", "global attributes", "id", "class", "style attribute", "title attribute", "hidden", "data-*", "aria-* basics"],
  "Input Types": ["input:text", "input:password", "input:email", "input:number", "input:date", "input:time", "input:checkbox", "input:radio", "input:file", "input:range", "input:color", "input:search", "input:url", "input:tel", "input:submit", "input:reset", "input:button", "input:hidden"],
  "Obsolete Elements": ["font", "center", "marquee", "big", "strike", "tt", "frameset", "frame"],
};

const htmlDescriptions: Record<string, string> = {
  html: "The root element that wraps the entire HTML document.", head: "Contains document metadata that is not shown as page content.", body: "Contains everything rendered in the browser viewport.", title: "Sets the page title shown in the browser tab and search results.", meta: "Provides metadata such as character encoding and viewport behavior.", link: "Connects the document to an external resource, commonly a stylesheet.", style: "Embeds CSS rules directly in an HTML document.", base: "Sets a base URL and default target for relative links.",
  "h1–h6": "Six heading levels that define the outline and hierarchy of a document.", p: "Represents a paragraph of related text.", br: "Creates a meaningful line break inside text.", hr: "Marks a thematic break between sections of content.", strong: "Marks text as strongly important or urgent.", b: "Draws attention to text without adding semantic importance.", em: "Adds stress emphasis that can change a sentence's meaning.", i: "Offsets text for an alternate voice, term, or idiom.", mark: "Highlights text as relevant in the current context.", small: "Represents side comments such as legal text or fine print.", del: "Marks content that was removed from a document.", ins: "Marks content that was added to a document.", sub: "Displays subscript text such as chemical formulas.", sup: "Displays superscript text such as exponents or references.", abbr: "Represents an abbreviation, optionally with its expansion.", cite: "Names the title of a creative work.", q: "Represents a short inline quotation.", blockquote: "Represents a longer quotation from another source.", code: "Marks a fragment of computer code.", pre: "Preserves whitespace and line breaks exactly as written.", kbd: "Represents user input from a keyboard or other device.", samp: "Represents sample output from a program.", var: "Represents a variable in math or programming.", time: "Represents a date, time, or duration in a machine-readable way.",
  a: "Creates a hyperlink to another page, file, location, or email address.", nav: "Identifies a major group of navigation links.", img: "Embeds an image with alternative text.", picture: "Offers multiple image sources for art direction or format support.", source: "Provides an alternative media resource for picture, audio, or video.", audio: "Embeds sound with optional browser controls.", video: "Embeds video with optional controls and fallback content.", track: "Adds timed text such as captions or subtitles to media.", iframe: "Embeds another HTML page in the current document.", embed: "Embeds external content handled by a browser plugin or viewer.", object: "Embeds an external resource with fallback content.", figure: "Groups self-contained media or content referenced by the main text.", figcaption: "Provides a caption for its parent figure.",
  ul: "Creates an unordered list where item order is not significant.", ol: "Creates an ordered list where sequence matters.", li: "Represents one item in an ordered or unordered list.", dl: "Creates a description list of terms and details.", dt: "Defines a term or name inside a description list.", dd: "Provides a description or value for a term in a description list.",
  table: "Represents tabular data arranged in rows and columns.", caption: "Gives a table an accessible title or description.", colgroup: "Groups table columns for shared styling or semantics.", col: "Describes one or more columns inside a colgroup.", thead: "Groups the header rows of a table.", tbody: "Groups the main data rows of a table.", tfoot: "Groups summary rows at the end of a table.", tr: "Creates a row of cells in a table.", th: "Creates a header cell that labels a row or column.", td: "Creates a standard data cell in a table.",
  form: "Groups controls that collect and submit user information.", label: "Provides an accessible name for a form control.", input: "Creates a versatile form control whose behavior depends on its type.", textarea: "Creates a multiline plain-text input.", button: "Creates an interactive button users can activate.", select: "Creates a menu of choices.", option: "Defines one choice inside a select or datalist.", optgroup: "Groups related options with a label.", fieldset: "Groups related form controls.", legend: "Provides a caption for a fieldset.", datalist: "Provides suggested values for an input.", output: "Displays the result of a calculation or user action.", progress: "Shows the completion progress of a task.", meter: "Shows a scalar value within a known range.",
  header: "Introduces a page or section with headings and supporting content.", main: "Contains the page's unique primary content.", section: "Groups a thematic section, usually with a heading.", article: "Represents self-contained content that could stand on its own.", aside: "Contains content indirectly related to the surrounding content.", footer: "Provides closing information for a page or section.", address: "Provides contact information for a person or organization related to the page.",
  details: "Creates a disclosure widget that users can open and close.", summary: "Provides the visible label for a details disclosure.", dialog: "Represents a modal or non-modal dialog box.", template: "Stores inert HTML that JavaScript can clone later.", slot: "Creates an insertion point inside a web component.", canvas: "Provides a bitmap drawing surface controlled with JavaScript.",
};

const attributeMap: Record<string, string[]> = {
  a: ["href — destination URL", "target — browsing context", "download — suggest a download", "rel — relationship and security hints"], img: ["src — image URL", "alt — text alternative", "width / height — reserve layout space", "loading — eager or lazy loading"], button: ["type — button, submit, or reset", "disabled — prevents interaction", "name / value — submitted form data", "form — associates an external form"], input: ["type — control behavior", "name — submitted field name", "value — current/default value", "required — prevents empty submission", "placeholder — short input hint"], form: ["action — submission URL", "method — get or post", "autocomplete — browser autofill behavior"], video: ["src — video URL", "controls — browser controls", "poster — preview image", "muted / autoplay / loop — playback behavior"], audio: ["src — audio URL", "controls — browser controls", "muted / autoplay / loop — playback behavior"], iframe: ["src — embedded page", "title — accessible name", "loading — eager or lazy", "sandbox — restrict embedded capabilities"], ol: ["start — first list number", "reversed — descending numbering", "type — numbering style"], td: ["colspan — columns occupied", "rowspan — rows occupied", "headers — associated header IDs"], th: ["scope — row, col, rowgroup, or colgroup", "colspan / rowspan — cells occupied"], time: ["datetime — machine-readable date or time"], details: ["open — disclosure starts expanded"], dialog: ["open — dialog is displayed"], meta: ["name — metadata type", "content — metadata value", "charset — document encoding", "http-equiv — HTTP-like instruction"], link: ["rel — resource relationship", "href — resource URL", "media — target media query", "type — resource MIME hint"],
};

function htmlExample(name: string) {
  if (name.startsWith("input:")) { const type = name.split(":")[1] ?? "text"; return `<label for="demo">${type} input</label>\n<input id="demo" type="${type}" ${["submit","reset","button"].includes(type) ? `value="Try ${type}"` : ""}>`; }
  const samples: Record<string, string> = {
    html: "<!doctype html>\n<html lang=\"en\">…</html>", head: "<head>\n  <meta charset=\"utf-8\">\n  <title>My page</title>\n</head>", body: "<body>\n  <main>Visible page content</main>\n</body>", title: "<title>HTML Notes — Document title</title>", meta: "<meta name=\"description\" content=\"A practical HTML guide.\">", link: "<link rel=\"stylesheet\" href=\"styles.css\">", style: "<style>\n  p { color: teal; }\n</style>\n<p>Styled text</p>", base: "<base href=\"https://example.com/docs/\">", "h1–h6": "<h1>Page title</h1>\n<h2>Major section</h2>\n<h3>Supporting topic</h3>", br: "<p>221B Baker Street<br>London, England</p>", hr: "<p>Chapter one</p>\n<hr>\n<p>Chapter two</p>", strong: "<p>Please <strong>save your work</strong> before leaving.</p>", b: "<p>New: <b>CSS Grid workshop</b></p>", em: "<p>I said <em>semantic</em>, not decorative.</p>", i: "<p>The term <i>viewport</i> describes the visible area.</p>", mark: "<p>Search result: learn <mark>flexbox</mark> today.</p>", small: "<p>Course pass <small>Terms apply.</small></p>", del: "<p>Price: <del>$49</del> $29</p>", ins: "<p>Agenda: HTML, CSS, <ins>accessibility</ins>.</p>", sub: "<p>Water is H<sub>2</sub>O.</p>", sup: "<p>2<sup>8</sup> equals 256.</p>", abbr: "<p><abbr title=\"Cascading Style Sheets\">CSS</abbr> styles the web.</p>", cite: "<p>Read <cite>HTML Living Standard</cite>.</p>", q: "<p>The tutor said, <q>Use meaningful markup.</q></p>", blockquote: "<blockquote cite=\"https://example.com\">The web is for everyone.</blockquote>", code: "<p>Use <code>display: grid</code> for a grid layout.</p>", pre: "<pre><code>&lt;h1&gt;Hello&lt;/h1&gt;</code></pre>", kbd: "<p>Press <kbd>Ctrl</kbd> + <kbd>K</kbd> to search.</p>", samp: "<p>Console: <samp>Build completed</samp></p>", var: "<p>Area = <var>w</var> × <var>h</var></p>", time: "<time datetime=\"2026-09-23\">23 September 2026</time>",
    a: "<a href=\"https://developer.mozilla.org\">Open MDN Web Docs</a>", nav: "<nav aria-label=\"Primary\"><a href=\"#learn\">Learn</a> · <a href=\"#practice\">Practice</a></nav>", img: "<img src=\"https://placehold.co/320x160/0e7490/ffffff?text=HTML\" alt=\"HTML study card\" width=\"320\" height=\"160\">", picture: "<picture><source media=\"(min-width: 600px)\" srcset=\"https://placehold.co/480x180\"><img src=\"https://placehold.co/280x180\" alt=\"Responsive placeholder\"></picture>", figure: "<figure><div class=\"media-demo\">Visual example</div><figcaption>Figure 1: A captioned visual.</figcaption></figure>", figcaption: "<figure><div class=\"media-demo\">CSS diagram</div><figcaption>The box model layers.</figcaption></figure>",
    ul: "<ul><li>Structure</li><li>Style</li><li>Behavior</li></ul>", ol: "<ol><li>Write HTML</li><li>Add CSS</li><li>Test the page</li></ol>", li: "<ul><li>One list item</li><li>Another list item</li></ul>", dl: "<dl><dt>HTML</dt><dd>Page structure</dd><dt>CSS</dt><dd>Visual presentation</dd></dl>", dt: "<dl><dt>Selector</dt><dd>A pattern that targets elements.</dd></dl>", dd: "<dl><dt>Property</dt><dd>A visual characteristic to change.</dd></dl>",
    table: "<table><caption>Study plan</caption><thead><tr><th>Day</th><th>Topic</th></tr></thead><tbody><tr><td>Mon</td><td>HTML</td></tr><tr><td>Tue</td><td>CSS</td></tr></tbody></table>", caption: "<table><caption>Weekly progress</caption><tr><th>Track</th><th>Done</th></tr><tr><td>HTML</td><td>6</td></tr></table>", th: "<table><tr><th scope=\"col\">Property</th><th scope=\"col\">Value</th></tr><tr><td>display</td><td>grid</td></tr></table>", td: "<table><tr><th>Language</th><td>HTML</td></tr><tr><th>Purpose</th><td>Structure</td></tr></table>",
    form: "<form onsubmit=\"event.preventDefault()\"><label for=\"name\">Name</label><input id=\"name\" name=\"name\"><button>Submit</button></form>", label: "<label for=\"topic\">Favorite topic</label><input id=\"topic\">", textarea: "<label for=\"notes\">Study notes</label><textarea id=\"notes\" rows=\"3\">Remember semantic HTML.</textarea>", button: "<button type=\"button\">Click me</button>", select: "<label for=\"level\">Level</label><select id=\"level\"><option>Beginner</option><option>Intermediate</option></select>", option: "<select aria-label=\"Topic\"><option>HTML</option><option selected>CSS</option></select>", optgroup: "<select aria-label=\"Lesson\"><optgroup label=\"HTML\"><option>Forms</option></optgroup><optgroup label=\"CSS\"><option>Grid</option></optgroup></select>", fieldset: "<fieldset><legend>Choose a track</legend><label><input type=\"radio\" name=\"track\"> HTML</label><label><input type=\"radio\" name=\"track\"> CSS</label></fieldset>", legend: "<fieldset><legend>Notifications</legend><label><input type=\"checkbox\"> Lesson reminders</label></fieldset>", datalist: "<label for=\"browser\">Browser</label><input id=\"browser\" list=\"browsers\"><datalist id=\"browsers\"><option value=\"Chrome\"><option value=\"Firefox\"></datalist>", output: "<form oninput=\"total.value=Number(a.value)+Number(b.value)\"><input id=\"a\" type=\"number\" value=\"2\"> + <input id=\"b\" type=\"number\" value=\"3\"> = <output name=\"total\" for=\"a b\">5</output></form>", progress: "<label for=\"course\">Course progress</label><progress id=\"course\" value=\"68\" max=\"100\">68%</progress>", meter: "<label for=\"score\">Quiz score</label><meter id=\"score\" min=\"0\" max=\"10\" value=\"8\">8/10</meter>",
    header: "<header><h1>Interactive Notes</h1><p>Learn the language of the web.</p></header>", main: "<header>Site header</header><main><h1>Unique page content</h1></main>", section: "<section><h2>HTML foundations</h2><p>Start with meaningful structure.</p></section>", article: "<article><h2>Understanding forms</h2><p>A self-contained lesson.</p></article>", aside: "<main><p>Main lesson text.</p><aside>Tip: labels improve accessibility.</aside></main>", footer: "<footer><p>Last reviewed September 2026.</p></footer>", address: "<address>Questions? <a href=\"mailto:tutor@example.com\">Email the tutor</a>.</address>", details: "<details><summary>What does HTML mean?</summary><p>HyperText Markup Language.</p></details>", summary: "<details><summary>Show the answer</summary><p>The cascade decides which CSS rule wins.</p></details>", dialog: "<button onclick=\"this.nextElementSibling.showModal()\">Open dialog</button><dialog><p>Practice completed!</p><button onclick=\"this.closest('dialog').close()\">Close</button></dialog>", canvas: "<canvas width=\"280\" height=\"100\" style=\"background:#cffafe\">Canvas fallback text</canvas>",
    comments: "<!-- This note is not rendered -->\n<p>This paragraph is visible.</p>", "global attributes": "<p id=\"intro\" class=\"lead\" title=\"Helpful detail\" data-level=\"beginner\">Inspect my attributes.</p>", id: "<h2 id=\"box-model\">The box model</h2><a href=\"#box-model\">Jump to heading</a>", class: "<p class=\"notice important\">A reusable class can style many elements.</p>", "style attribute": "<p style=\"color: teal; font-weight: 700\">Inline styled text</p>", "title attribute": "<abbr title=\"HyperText Markup Language\">HTML</abbr>", hidden: "<p>This is visible.</p><p hidden>This is removed from display and accessibility.</p>", "data-*": "<button data-topic=\"flexbox\" data-level=\"beginner\">Start lesson</button>", "aria-* basics": "<button aria-expanded=\"false\" aria-controls=\"tips\">Show tips</button><div id=\"tips\" hidden>Helpful tips</div>",
  };
  return samples[name] ?? `<div class="demo"><${name}>${name} example</${name}></div>`;
}

function htmlLesson(name: string, category: string): Lesson {
  const obsolete = category === "Obsolete Elements";
  const isInput = name.startsWith("input:");
  const inputType = name.split(":")[1] ?? "text";
  const display = isInput ? `input type="${inputType}"` : name;
  const element = isInput ? "input" : name;
  const description = obsolete ? `The <${name}> element is obsolete and must not be used in modern HTML.` : htmlDescriptions[name] ?? (isInput ? `Creates an input control specialized for ${inputType} values or actions.` : `The <${name}> element provides a specialized structure or behavior in an HTML document.`);
  return {
    id: `ref-html-${name.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}`,
    track: "html", category, title: `<${display}>`, label: obsolete ? "Obsolete — learn the modern replacement" : description,
    summary: description, explanation: `${description} ${obsolete ? "It appears in older code, but CSS and semantic elements provide accessible modern alternatives." : "Use it for its meaning and native browser behavior rather than for appearance alone."}`,
    syntax: isInput ? `<input type="${inputType}" name="example">` : name === "comments" ? "<!-- A private note in the source -->" : name.includes("attribute") || ["id","class","hidden","data-*","aria-* basics","global attributes"].includes(name) ? htmlExample(name) : `<${element}>Content</${element}>`,
    html: htmlExample(name),
    css: "body { font-family: system-ui; line-height: 1.6; }\nlabel { display: block; margin-bottom: .4rem; font-weight: 700; }\ninput, textarea, select, button { padding: .65rem; border: 1px solid #94a3b8; border-radius: 7px; }\nbutton { cursor: pointer; background: #0e7490; color: white; }\ntable { border-collapse: collapse; }\nth, td { border: 1px solid #cbd5e1; padding: .6rem; }\n.media-demo { padding: 2rem; background: #cffafe; border-radius: 8px; }",
    note: obsolete ? `Do not use <${name}> in new work. Learn it only so you can recognize and replace it in legacy pages.` : `Use ${display} when its built-in meaning matches your content. Keep content accessible and avoid using it only to imitate a visual style.`,
    tags: [name, category, "HTML reference"], attributes: isInput ? ["type — selects the control", "name — submission key", "value — current value", "required — requires a value", "disabled — prevents interaction"] : attributeMap[element] ?? ["Global attributes — id, class, title, hidden, data-*, and aria-* where appropriate"],
    related: isInput ? ["input", "label", "form"] : category === "Obsolete Elements" ? ["CSS", "semantic HTML"] : ["global attributes", category], obsolete,
  };
}

const cssGroups: Record<string, string[]> = {
  Selectors: ["element selector", "class selector", "ID selector", "universal selector", "attribute selector", "descendant selector", "child selector", "adjacent sibling", "general sibling", "pseudo-class", "pseudo-element"],
  "Colors & Backgrounds": ["color", "background", "background-color", "background-image", "background-size", "background-position", "background-repeat", "background-attachment", "opacity", "gradients"],
  Typography: ["font-family", "font-size", "font-weight", "font-style", "font-variant", "line-height", "letter-spacing", "word-spacing", "text-align", "text-decoration", "text-transform", "text-indent", "text-shadow", "white-space", "word-break", "overflow-wrap"],
  "Box Model": ["width", "height", "min-width", "max-width", "min-height", "max-height", "margin", "padding", "border", "border-width", "border-style", "border-color", "border-radius", "box-sizing", "box-shadow", "outline"],
  "Display & Visibility": ["display", "visibility", "overflow", "overflow-x", "overflow-y", "display: block", "display: inline", "display: inline-block", "display: none"],
  Flexbox: ["display: flex", "flex-direction", "flex-wrap", "flex-flow", "justify-content", "align-items", "align-content", "gap", "row-gap", "column-gap", "flex", "flex-grow", "flex-shrink", "flex-basis", "order", "align-self"],
  Grid: ["display: grid", "grid-template-columns", "grid-template-rows", "grid-template-areas", "grid-column", "grid-column-start", "grid-column-end", "grid-row", "grid-row-start", "grid-row-end", "justify-items", "place-items", "grid-auto-flow", "grid-auto-columns", "grid-auto-rows"],
  Positioning: ["position: static", "position: relative", "position: absolute", "position: fixed", "position: sticky", "top", "right", "bottom", "left", "inset", "z-index"],
  Transform: ["transform", "transform-origin", "translate", "translateX", "translateY", "scale", "rotate", "skew", "skewX", "skewY"],
  Transitions: ["transition", "transition-property", "transition-duration", "transition-delay", "transition-timing-function"],
  Animations: ["animation", "animation-name", "animation-duration", "animation-delay", "animation-iteration-count", "animation-direction", "animation-fill-mode", "animation-play-state", "animation-timing-function", "@keyframes"],
  Responsive: ["media queries", "breakpoints", "%", "px", "em", "rem", "vw", "vh", "vmin", "vmax", "clamp()"],
};

const cssValues: Record<string, string[]> = {
  color: ["named colors", "hex", "rgb()", "hsl()", "oklch()", "currentColor"], display: ["block", "inline", "inline-block", "flex", "grid", "none"], position: ["static", "relative", "absolute", "fixed", "sticky"], overflow: ["visible", "hidden", "clip", "scroll", "auto"], "justify-content": ["start", "center", "end", "space-between", "space-around", "space-evenly"], "align-items": ["stretch", "start", "center", "end", "baseline"], "flex-direction": ["row", "row-reverse", "column", "column-reverse"], "flex-wrap": ["nowrap", "wrap", "wrap-reverse"], "background-size": ["auto", "cover", "contain", "length / percentage"], "text-align": ["start", "center", "end", "justify"], "box-sizing": ["content-box", "border-box"], "white-space": ["normal", "nowrap", "pre", "pre-wrap"], visibility: ["visible", "hidden", "collapse"],
};

function cssProperty(name: string): string { return name.includes(": ") ? (name.split(":")[0] ?? name) : name; }
function cssExample(name: string, category: string) {
  const prop = cssProperty(name);
  if (category === "Selectors") {
    const selector: Record<string,string> = { "element selector":"p", "class selector":".note", "ID selector":"#intro", "universal selector":"*", "attribute selector":"input[type=\"email\"]", "descendant selector":"article p", "child selector":"nav > a", "adjacent sibling":"h2 + p", "general sibling":"h2 ~ p", "pseudo-class":"button:hover", "pseudo-element":"p::first-letter" };
    return `${selector[name] ?? ".example"} {\n  color: #0e7490;\n  font-weight: 700;\n}`;
  }
  if (category === "Flexbox") return `.demo {\n  display: flex;\n  ${prop}: ${prop.includes("gap") ? "1rem" : prop.includes("direction") ? "row-reverse" : prop.includes("wrap") ? "wrap" : prop.includes("justify") ? "space-between" : prop.includes("align") ? "center" : prop === "flex" ? "1 1 8rem" : prop === "order" ? "2" : "1"};\n}`;
  if (category === "Grid") return `.demo {\n  display: grid;\n  ${prop}: ${prop.includes("template") ? "repeat(3, 1fr)" : prop.includes("gap") ? "1rem" : prop.includes("flow") ? "column" : prop.includes("items") ? "center" : "span 2"};\n}`;
  if (category === "Positioning") return `.stage { position: relative; }\n.demo {\n  ${name.startsWith("position:") ? name : "position: absolute;"}\n  ${name.startsWith("position:") ? "inset: 1rem auto auto 1rem" : `${prop}: 1rem`};\n}`;
  if (category === "Transform") return `.demo {\n  ${prop === name ? `${prop}: ${prop === "scale" ? "1.12" : prop.startsWith("rotate") ? "8deg" : prop.startsWith("skew") ? "8deg" : prop === "transform-origin" ? "top left" : "16px 0"};` : "transform: translateX(16px);"}\n}`;
  if (category === "Transitions") return `.demo {\n  ${prop}: ${prop === "transition" ? "transform 300ms ease" : prop.includes("duration") ? "300ms" : prop.includes("delay") ? "120ms" : prop.includes("timing") ? "ease-in-out" : "transform"};\n}\n.demo:hover { transform: translateY(-8px); }`;
  if (category === "Animations") return `@keyframes float { 50% { transform: translateY(-10px); } }\n.demo {\n  ${prop === "@keyframes" ? "animation: float 1.5s ease-in-out infinite" : `${prop}: ${prop.includes("duration") ? "1.5s" : prop.includes("delay") ? ".2s" : prop.includes("iteration") ? "infinite" : prop.includes("direction") ? "alternate" : prop.includes("fill") ? "both" : prop.includes("play") ? "running" : prop.includes("timing") ? "ease-in-out" : prop === "animation-name" ? "float" : "float 1.5s ease-in-out infinite"}`};\n}`;
  if (category === "Responsive") return name === "media queries" || name === "breakpoints" ? `.demo { display: grid; gap: 1rem; }\n@media (min-width: 40rem) {\n  .demo { grid-template-columns: 1fr 1fr; }\n}` : `.demo { width: ${name === "clamp()" ? "clamp(12rem, 50vw, 28rem)" : `60${name}`}; }`;
  const value: Record<string,string> = { color:"#0e7490", background:"linear-gradient(135deg, #cffafe, #fef3c7)", "background-color":"#cffafe", "background-image":"linear-gradient(135deg, #0891b2, #f59e0b)", "background-size":"cover", "background-position":"center", "background-repeat":"no-repeat", "background-attachment":"fixed", opacity:".65", gradients:"linear-gradient(135deg, #0891b2, #f59e0b)", "font-family":"system-ui, sans-serif", "font-size":"1.5rem", "font-weight":"700", "font-style":"italic", "font-variant":"small-caps", "line-height":"1.7", "letter-spacing":".08em", "word-spacing":".3em", "text-align":"center", "text-decoration":"underline wavy #0891b2", "text-transform":"uppercase", "text-indent":"2rem", "text-shadow":"2px 2px 0 #a5f3fc", "white-space":"nowrap", "word-break":"break-all", "overflow-wrap":"anywhere", width:"70%", height:"120px", "min-width":"12rem", "max-width":"28rem", "min-height":"6rem", "max-height":"12rem", margin:"2rem auto", padding:"1.5rem", border:"3px solid #0891b2", "border-width":"6px", "border-style":"dashed", "border-color":"#f59e0b", "border-radius":"18px", "box-sizing":"border-box", "box-shadow":"0 16px 35px #0e749033", outline:"3px solid #f59e0b", visibility:"hidden", overflow:"auto", "overflow-x":"scroll", "overflow-y":"hidden" };
  if (name.startsWith("display:")) return `.demo { ${name}; }`;
  return `.demo {\n  ${prop === "gradients" ? "background" : prop}: ${value[name] ?? "initial"};\n}`;
}

function cssLesson(name: string, category: string): Lesson {
  const prop = cssProperty(name);
  const code = cssExample(name, category);
  const isSelector = category === "Selectors";
  const values = cssValues[prop] ?? (category === "Responsive" ? ["relative unit", "absolute unit", "fluid function"] : ["See syntax example", "global values: inherit, initial, unset"]);
  return {
    id: `ref-css-${name.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}`, track: "css", category, title: name, label: `${category} reference`,
    summary: isSelector ? `${name} targets a specific relationship or state in the document.` : `${name} controls an important part of presentation in CSS.`,
    explanation: isSelector ? `The ${name} matches elements using a clear structural rule. Keep selectors as simple and reusable as possible.` : `The ${name} property controls ${category.toLowerCase()} behavior. Compare its common values in the live example and choose the value that communicates your intended layout or visual state.`,
    syntax: code, html: `<div class="demo"><span>One</span><span>Two</span><span>Three</span></div>`, css: `.demo { min-height: 130px; padding: 1.25rem; border: 1px solid #94a3b8; border-radius: 12px; background-color: #f8fafc; font: 700 1rem system-ui; }\n.demo span { display: inline-block; margin: .35rem; padding: .7rem; border-radius: 7px; background: #cffafe; color: #155e75; }\n${code}`,
    note: `Test ${name} with real content and at narrow widths. Prefer a simple declaration first, then add complexity only when the layout requires it.`,
    tags: [name, category, "CSS reference"], attributes: values.map((value) => `${value} — common value or form`), related: [category, prop === name ? "CSS cascade" : prop],
  };
}

const htmlLessons = Object.entries(htmlGroups).flatMap(([category, names]) => names.map((name) => htmlLesson(name, category)));
const cssLessons = Object.entries(cssGroups).flatMap(([category, names]) => names.map((name) => cssLesson(name, category)));

export const referenceLessons: Lesson[] = [...htmlLessons, ...cssLessons];